# Generated by Django 2.2.7 on 2019-12-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20191213_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, null=True, related_name='attevents', to='events.Attendee'),
        ),
    ]
